apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-role-flask
rules:
- apiGroups: [""]
  resources: ["pods","services","ConstraintTemplate"]
  verbs: ["watch","list","get", "create", "update", "patch", "delete"]
