apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-custom-api-role
rules:
- apiGroups: ["templates.gatekeeper.sh","constraints.gatekeeper.sh"]
  resources: ["*"]
  verbs: ["watch","list","get", "create", "update", "patch", "delete"]
- apiGroups: ["constraints.gatekeeper.sh"]
  resources: ["k8sdenyname3"]
  verbs: ["*"]
