apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 5000
      nodePort: 30000
  selector:
    app: my-flask-app
  externalIPs:
   - 3.89.143.5
