apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybackend-deployment
  labels:
    app: mybackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybackend
  template:
    metadata:
      labels:
        app: mybackend
    spec:
      serviceAccountName: my-svc-account-v1
      containers:
      - name: mybackend
        image: bouzaianerima/backend:87.0
        ports:
        - containerPort: 5000
#        securityContext:
 #         allowPrivilegeEscalation: false
  #        runAsNonRoot: true  
   #       runAsUser: 1000     

