apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-config-ip-metalb
  namespace: metallb-system
spec:
  addresses:
  - 54.161.128.131-54.161.128.131 #IP WORKER AND NOT MASTER!!!!!!!
