apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-config-ip-metalb
  namespace: metallb-system
spec:
  addresses:
  - 54.157.156.141-54.157.156.141 #IP WORKER AND NOT MASTER!!!!!!!
