apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-config-ip-metalb
  namespace: metallb-system
spec:
  addresses:
  - 18.210.19.121-18.210.19.121 #IP WORKER AND NOT MASTER!!!!!!!
