apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-v1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

